# -*- coding: utf-8 -*-
"""Automate_Muhammad Eka Mandiri Sujanto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yx2NykQKoCmZvzRQmeP7tpJtgQZcJW8N
"""

pip install pandas seaborn scikit-learn

import pandas as pd

from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler
)

def preprocess():

    df = pd.read_csv(
        "/content/WA_Fn-UseC_-Telco-Customer-Churn.csv"
    )

    df.drop(
        columns=["customerID"],
        inplace=True
    )

    df["TotalCharges"] = pd.to_numeric(
        df["TotalCharges"],
        errors="coerce"
    )

    df.fillna(
        df.median(numeric_only=True),
        inplace=True
    )

    le = LabelEncoder()

    for col in df.select_dtypes(
        include="object"
    ).columns:

        df[col] = le.fit_transform(
            df[col]
        )

    scaler = StandardScaler()

    X = df.drop(
        "Churn",
        axis=1
    )

    X = scaler.fit_transform(X)

    processed = pd.DataFrame(
        X,
        columns=df.drop(
            "Churn",
            axis=1
        ).columns
    )

    processed["Churn"] = df["Churn"]

    processed.to_csv(
        "customer_churn_processed.csv",
        index=False
    )

if __name__ == "__main__":
    preprocess()