name: Preprocessing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.2"

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn

      - name: Run preprocessing script
        run: python preprocessing/automate_muhammad_eka_mandiri_sujanto.py

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          path: preprocessing/Telco Customer Churn_preprocessing
